version: '3.7'

services:
  web:
    build: ./app
    command: python teacher_student/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_teacher_student
      - POSTGRES_PASSWORD=password_teacher_student
      - POSTGRES_DB=db_teacher_student

volumes:
  postgres_data: