# Generated by Django 3.0.7 on 2021-05-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stars', models.ManyToManyField(null=True, related_name='teachers', related_query_name='stars', to='crud.Teachers')),
                ('teachers', models.ManyToManyField(null=True, to='crud.Teachers')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
